options {
        directory "/var/cache/bind";

        listen-on port 25566 { 127.0.0.1; };
        listen-on-v6 { none; };

        forwarders {
                8.8.8.8;
                8.8.4.4;
        };

        dnssec-validation no;
        recursion yes;
        allow-query { any; };
        allow-recursion { any; };

        auth-nxdomain no;
};

zone "example.com" {
  type primary;
  file "example.com";
  notify no;
  allow-transfer {
    any;
  };
};

zone "0.0.127.in-addr.arpa" {
  type primary;
  file "0.0.127.in-addr.arpa";
  notify no;
  allow-transfer {
    any;
  };
};
