
fandango_login:
  driver                     = plaintext
  public_name                = LOGIN
  server_set_id              = $auth1
  server_prompts             = <| Username: | Password:
  server_condition           = ${if and{{eq{$auth1}{the_user}}{eq{$auth2}{the_password}}}{yes}{no}}
