[package]
name = "fandango-native"
version = "1.1.1"
edition = "2021"

[lib]
name = "native"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.29", features = ["experimental-inspect"] }

[build-dependencies]
cmake = "0.1"

[target.'cfg(windows)'.build-dependencies]
python3-dll-a = "0.2"
