[Interface]
Address = 10.13.13.2/32
PrivateKey = 2HfMsoxG4PsoK4mrH4obxS42sBJcBivXJKDZZoTp/U8=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = Ui+tZoBJP6gufK/8oppEoHzcl1AdtihQQH4eWMs+Hm4=
PresharedKey = Mre8QycOhWQE0tMVayZT8bfQc8l045CPFCbO/2Mczoo=
Endpoint = 92.211.25.51:51820
AllowedIPs = 0.0.0.0/0
