[Interface]
Address = 10.13.13.1
ListenPort = 51820
PrivateKey = kCE91+RlRL+KBtzlpEuQxOVvTJbUAnT3kJtuUw5KYEw=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE

[Peer]
# peer1
PublicKey = 19VH9WvCowewk8C7ruI92vAJB1yyB02KtGfsoHKsU1E=
PresharedKey = Mre8QycOhWQE0tMVayZT8bfQc8l045CPFCbO/2Mczoo=
AllowedIPs = 10.13.13.2/32

