name: "Benchmarks: Run on External PRs"

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  benchmark_fork_pr_branch:
    name: Run Fork PR Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Fandango
        uses: ./.github/workflows/setup-fandango
        with:
          python-version: 3.13
          needs-sudo: true
          target: test

      - name: Run Benchmarks
        run: |
          pytest -n 0 --benchmark-json results.json tests/test_benchmarks.py
      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v4
        with:
          name: results.json
          path: ./results.json
      - name: Upload GitHub Pull Request Event
        uses: actions/upload-artifact@v4
        with:
          name: event.json
          path: ${{ github.event_path }}
