name: Build & Upload to PyPI and Docker Hub

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  validate_branch:
    name: Validate release source branch
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.sha.outputs.commit }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get release target commit
        id: sha
        run: |
          echo "commit=${{ github.event.release.target_commitish }}" >> $GITHUB_OUTPUT

      - name: Ensure release is from release branch
        run: |
          git fetch origin release
          if git merge-base --is-ancestor ${{ github.event.release.target_commitish }} origin/release; then
            echo "✅ Valid release source"
          else
            echo "❌ Releases must be created from the release branch."
            exit 1
          fi

  build_wheels:
    name: Build wheels for ${{ matrix.os }}
    needs: validate_branch
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux-intel
            runs-on: ubuntu-latest
          - os: linux-arm
            runs-on: ubuntu-24.04-arm
          - os: macos-arm
            runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.2
        env:
          FANDANGO_REQUIRE_BINARY_BUILD: "1"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    needs: validate_branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  upload_pypi:
    name: Upload to PyPI
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/fandango-fuzzer
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

  docker_build_and_push:
    name: Build and Push Docker Image
    needs: validate_branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_REPO }}:latest
