name: GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - docs/**
  workflow_dispatch: # Allows manual triggering from the Actions tab

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the source repository
    - name: Checkout the source repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13
        cache: "pip"

    # Step 3: Ensure Graphviz system package is installed
    - name: Install Graphviz system package
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz

    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
        pip install -e ".[book]"

    # Step 5: Locate Fandango and add to PATH
    - name: Locate Fandango and add to PATH
      run: |
        which fandango
        echo "/opt/hostedtoolcache/Python/3.13.1/x64/bin/fandango" >> $GITHUB_PATH
        fandango --help

    # Step 6: Build the documentation
    - name: Build the book
      run: |
        make html

    # Step 7: Clone the target repository
    - name: Clone the target repository
      run: |
        git clone https://github.com/fandango-fuzzer/fandango-fuzzer.github.io.git gh-pages

    # Step 8: Copy the built HTML files to the target repository
    - name: Copy built files to the target repository
      run: |
        cp -r docs/_build/html/* gh-pages/

    # Step 9: Commit and push changes to the target repository
    - name: Deploy to GitHub Pages
      run: |
        cd gh-pages
        git config --global user.name "${{ secrets.CI_COMMIT_AUTHOR }}"
        git config --global user.email "${{ secrets.CI_COMMIT_EMAIL }}"
        git add .
        git commit -m "Update GitHub Pages site" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/fandango-fuzzer/fandango-fuzzer.github.io.git main
